### ISSUE TITLE
There is not valid symbols

### ISSUE THREAD

**Issue by iovigi** [JKorf/Bitfinex.Net#140]
Hello,

Thank you so much for developing and supporting the APIs for many cryptocurrencies exchanges.  
I want to report one bug, it is related with validator for symbols. 
I am trying to get symbols with.GetSymbolDetailsAsync() and for this method, there isn't one pair, which is valid according to https://github.com/JKorf/Bitfinex.Net/blob/master/Bitfinex.Net/BitfinexHelpers.cs . 

Thank you again for libraries.

**Comment by JKorf** [comment]
Hi, 
It's because the `GetSymbolDetailsAsync` uses the V1 API endpoint https://docs.bitfinex.com/v1/reference#rest-public-symbol-details, which return the symbol as lowercase and without prefix. The V2 API endpoints expect symbols to have a 't' prefix for trading symbols, of 'f' prefix for funding symbols. So symbols from the `GetSymbolDetailsAsync` endpoint will need a small conversion: `"t" + symbol.ToUpper()`.

The V1 endpoint is still used because there is no easily accessible V2 replacement.

**Comment by iovigi** [comment]
Thank you :)
