### ISSUE TITLE
Trades stream didn't restore after connection lost

### ISSUE THREAD

**Issue by NektoDron** [JKorf/Bitfinex.Net#29]
15:36:06.31[32]DEBUG:[bitfinex] Loaded 1 ticks for btcusd:Bitfinex. Last is 260060300
15:36:06.32[32]DEBUG:[bitfinex] Loaded 1 ticks for btcusd:Bitfinex. Last is 260060301
15:36:06.35[32]DEBUG:[bitfinex] Loaded 1 ticks for btcusd:Bitfinex. Last is 260060299
15:36:06.35[32]DEBUG:sec btcusd:Bitfinex mydate 21.06.2018 12:36:06 newdate 21.06.2018 12:36:06 clear 3 trades. findById=True id=260060299 before=801
15:36:06.36[32]DEBUG:[bitfinex] Loaded 1 ticks for btcusd:Bitfinex. Last is 260060301
15:36:06.36[32]DEBUG:[bitfinex] Loaded 1 ticks for btcusd:Bitfinex. Last is 260060300
15:36:06.36[32]DEBUG:sec btcusd:Bitfinex mydate 21.06.2018 12:36:06 newdate 21.06.2018 12:36:06 clear 1 trades. findById=True id=260060300 before=802
2018/06/21 15:36:17:240 | Info | Received status code 20051, going to reconnect the websocket
15:36:17.24[32]DEBUG:[bitfinex] API: 2018/06/21 15:36:17:240 | Info | Received status code 20051, going to reconnect the websocket
2018/06/21 15:36:20:149 | Info | Socket connection established
2018/06/21 15:36:20:150 | Info | Websocket version: 2, platform status: operational
15:36:20.17[13]DEBUG:[bitfinex] API: 2018/06/21 15:36:20:149 | Info | Socket connection established
15:36:20.21[40]DEBUG:[bitfinex] API: 2018/06/21 15:36:20:150 | Info | Websocket version: 2, platform status: operational
2018/06/21 15:36:20:230 | Info | Authentication successful
15:36:20.23[40]DEBUG:[bitfinex] API: 2018/06/21 15:36:20:230 | Info | Authentication successful

After it no more trades was received.

**Comment by ciottied** [comment]
Same here.
It appears that after connection/reconnection some subscriptions are lost.
In my experience Candles and Trades are the "less robust" and the more likely to be lost.

**Comment by JKorf** [comment]
I've done some rework on the socket client, please try again with the latest version (v1.0.13)

**Comment by JKorf** [comment]
This should be fixed in latest versions, if not please re-open the issue

**Comment by ciottied** [comment]
Testing 1.013, and I confirm that some times Candle subscriptions are lost on reconnect.
I implemented a sort of keepalive mechanism, that resets connection (close/reopen socket) after 300 secs without data arrivals.

That is possible with candles, because there is a continuous stream of data, but this is not the case for other subscribed streams like orders or trades, for which you know that subscription is down only when You see order sent or traded executed without receiving data.

However, at the moment (approx 36 hours testing) I didn't detect trades or order subscriptions lost.

Regards.

edc
