### ISSUE TITLE
Orderbook some Questions?

### ISSUE THREAD

**Issue by polopua** [JKorf/Bitfinex.Net#85]
Hello im new in c#,

Is there some Orderbook Read/Write/Mapping Example available? 
Whats Ask/Bid in the Respone with Precision Level 0 und a Limit of 25?
And how i can Mapping the Updates? ;o

thx

**Comment by JKorf** [comment]
Hi, I'm currently working on an order book implementation to make it easier to use, but I'm not sure when it will be done.
In general the workflow would be as follows:
1. Subscribe to order book updates using the websocket
2. Cache update messages
3. Request an order book snapshot via the rest API
4. Replay the update messages on the order book ( make sure to discard the update messages which were already in the order book )
5. Update the order book with the new updates from the socket.

In Bitfinex it works a little different since a snapshot is received when subscribing on the websocket which makes it a little easier:
1. Subscribe to order book updates using the websocket
2. Save the initially received order book state
3. Update the order book with messages received after that

Note that on Bitfinex updates with quantity > 0 are bids and updates with quantity < 0 are asks.

**Comment by polopua** [comment]
Mhmmm, looks like a bit strange for me..

> Note that on Bitfinex updates with quantity > 0 are bids and updates with quantity < 0 are asks.

How i know then, when > 0 are bids and < 0 are asks, what is then + or - the Amount/Order from Orderbook?

Have you some Code Snipped for me how looks that right/correctly?

**Comment by JKorf** [comment]
Sorry I don't have a snippet for you at the moment, but this is what the API documentation says: 
````
Algorithm to create and keep a book instance updated

1. subscribe to channel
2. receive the book snapshot and create your in-memory book structure
3. when count > 0 then you have to add or update the price level
3.1 if amount > 0 then add/update bids
3.2 if amount < 0 then add/update asks
4. when count = 0 then you have to delete the price level.
4.1 if amount = 1 then remove from bids
4.2 if amount = -1 then remove from asks
````

**Comment by polopua** [comment]
> Sorry I don't have a snippet for you at the moment, but this is what the API documentation says:
> Algorithm to create and keep a book instance updated
> 
> 1. subscribe to channel
> 2. receive the book snapshot and create your in-memory book structure
> 3. when count > 0 then you have to add or update the price level
> 3.1 if amount > 0 then add/update bids
> 3.2 if amount < 0 then add/update asks
> 4. when count = 0 then you have to delete the price level.
> 4.1 if amount = 1 then remove from bids
> 4.2 if amount = -1 then remove from asks

Allright thanks, this answer is help enough :)
